### ISSUE TITLE
Wrong error message when creating a content type object without permissions

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.api#160]
If you have a folder created, let's say, by the site admin, and then you try to add an object inside the folder with an user that doesn't have permissions, you get a **Disallowed subobject type** error instead of a permission one.

this is very confusing.

```python
Error in test test_view_synchronise (my.project.tests.test_synchronise.ContentTypeTestCase)
Traceback (most recent call last):
  File "/home/hvelarde/buildout.python/parts/opt/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/home/hvelarde/simplesconsultoria/my.project/src/my/project/tests/test_synchronise.py", line 50, in test_view_sync
    counter = view.create_content()
  File "/home/hvelarde/simplesconsultoria/my.project/src/my/project/sync/synchronise.py", line 73, in create_content
    o = self.create_mytype(base_folder['container'], par)
  File "/home/hvelarde/simplesconsultoria/my.project/src/my/project/sync/synchronise.py", line 113, in create_mytype
    folder, type='MyType', id=oId, title=title)
  File "<string>", line 2, in create
  File "/home/hvelarde/.buildout/eggs/plone.api-1.1.0-py2.7.egg/plone/api/validation.py", line 70, in wrapped
    return f(*args, **kwargs)
  File "<string>", line 2, in create
  File "/home/hvelarde/.buildout/eggs/plone.api-1.1.0-py2.7.egg/plone/api/validation.py", line 131, in wrapped
    return f(*args, **kwargs)
  File "/home/hvelarde/.buildout/eggs/plone.api-1.1.0-py2.7.egg/plone/api/content.py", line 84, in create
    "{2}".format(type, '\n'.join(sorted(types)), e.message)
InvalidParameterError: Cannot add a 'MyType' object to the container.
Allowed types are:
MyType
Disallowed subobject type: MyType
```

**Comment by jaroel** [comment]
What needs to be done, and who is going to do it?

**Comment by adamcheasley** [comment]
I think we have a pretty clear plan. If I manage to get #204 done in the next couple of weeks, I will take a look at this one too.

**Comment by adamcheasley** [comment]
What exception would be best to raise here? AccessControl.Unauthorized?

**Comment by jaroel** [comment]
Works just fine on master:

```python
>>> with api.env.adopt_roles(roles='Manager'): my_folder = api.content.create(type='Folder', id='my_folder', container=api.portal.get())
>>> my_folder
<ATFolder at /plone/my_folder>
>>> api.content.get_state(my_folder)
'private'
>>> with api.env.adopt_roles(roles='Anonymous'): my_doc = api.content.create(type='Document', id='my_doc', container=my_folder)
*** Unauthorized: Cannot create Document
```

**Comment by jaroel** [comment]
We'd better add additional helpful info to the original exception by checking the permissions 'cmf.AddPortalContent' and the permission defined in the contenttypes' FTI.add_permission.

See http://stackoverflow.com/questions/9157210/how-do-i-raise-the-same-exception-with-a-custom-message-in-python for an example on replacing the message.

**Comment by jaroel** [comment]
Perhaps you could provide a test that shows what is happening to you?

This test shows that content.create raises an Unauthorized:
```python
    def test_create_raises_authorized(self):
        from plone.api.env import adopt_roles
        from plone.api import content
        from AccessControl import Unauthorized
        with adopt_roles('Manager'):
            folder = content.create(type='Folder', id='restricted_folder', container=self.portal)

        with self.assertRaises(Unauthorized):
            with adopt_roles('Anonymous'):
                doc = content.create(type='Document', id='my_doc', container=folder)
```

**Comment by adamcheasley** [comment]
I will stop development on this until we can confirm the issue.

**Comment by hvelarde** [comment]
done, please review and merge.

**Comment by hvelarde** [comment]
@gforcada why did you close the issue? the problem is still there as my branch shows.

**Comment by jaroel** [comment]
I've got an implementation in this branch: https://github.com/plone/plone.api/tree/content-create-check-permission
I think I can get this in plone.dexterity instead of here.

**Comment by jaroel** [comment]
The permission check is done in https://github.com/plone/plone.dexterity/pull/38

**Comment by hvelarde** [comment]
@jaroel cool!

**Comment by jaroel** [comment]
This is fixed in plone.dexterity >= 2.3.3
