### ISSUE TITLE
getSite() returns None when using zope debug console

### ISSUE THREAD

**Issue by zupo** [plone/plone.api#20]
Trying to get the portal object in a debug console session ($ bin/instance debug) fails:

```
>>> from Products.CMFPlone.Portal import PloneSite
>>> from plone import api
>>> isinstance(api.portal.get(), PloneSite)
False
```

Running the same code in a pdb session in a running instance ($ bin/instance fg) works as expected:

```
(Pdb) from plone import api
(Pdb) from Products.CMFPlone.Portal import PloneSite
(Pdb) isinstance(api.portal.get(), PloneSite)
True
```

**Comment by rodfersou** [comment]
more about this:

    ➜  ./bin/instance -O Plone debug 
    Starting debugger (the name "app" is bound to the top-level Zope object)
    >>> from plone import api
    >>> from datetime import datetime
    >>> today = datetime.now()
    >>> api.portal.get_localized_time(datetime=today)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "<string>", line 2, in get_localized_time
      File "/srv/cache/eggs/plone.api-1.3.2-py2.7.egg/plone/api/validation.py", line 70, in wrapped
        return f(*args, **kwargs)
      File "/srv/cache/eggs/plone.api-1.3.2-py2.7.egg/plone/api/portal.py", line 189, in get_localized_time
        tool = get_tool(name='translation_service')
      File "<string>", line 2, in get_tool
      File "/srv/cache/eggs/plone.api-1.3.2-py2.7.egg/plone/api/validation.py", line 70, in wrapped
        return f(*args, **kwargs)
      File "/srv/cache/eggs/plone.api-1.3.2-py2.7.egg/plone/api/portal.py", line 90, in get_tool
        return getToolByName(get(), name)
      File "/srv/cache/eggs/plone.api-1.3.2-py2.7.egg/plone/api/portal.py", line 54, in get
        "Unable to get the portal object. More info on "
    plone.api.exc.CannotGetPortalError: Unable to get the portal object. More info on https://ploneapi.readthedocs.org/en/latest/api/exceptions.html#plone.api.exc.CannotGetPortalError


    ➜  grep -i zope2instance bin/instance 
    '/srv/cache/eggs/plone.recipe.zope2instance-4.2.15-py2.7.egg',

**Comment by rodfersou** [comment]
Also the site pointed in the exception is not the right place of the exception documentation https://ploneapi.readthedocs.org/en/latest/api/exceptions.html#plone.api.exc.CannotGetPortalError

**Comment by rodfersou** [comment]
My problem here was that I was using ``bin/instance debug -O Plone`` instead of ``bin/instance -O Plone debug``

Now it is working here
