### ISSUE TITLE
api.group.get_roles() fails with AutoGroup

### ISSUE THREAD

**Issue by pbauer** [plone/plone.api#350]
getting local roles fails for the AutoGroup 'AuthenticatedUsers' :

```
Error in test test_local_roles_without_inheritance_for_builtin_groups (plone.api.tests.test_group.TestPloneApiGroup)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 398, in debug
    getattr(self, self._testMethodName)()
  File "/Users/philip/workspace/kbo/src-mrd/plone.api/src/plone/api/tests/test_group.py", line 574, in test_local_roles_without_inheritance_for_builtin_groups
    api.group.get_roles(groupname='AuthenticatedUsers', obj=folder, inherit=False)
  File "<decorator-gen-53>", line 2, in get_roles
  File "/Users/philip/workspace/kbo/src-mrd/plone.api/src/plone/api/validation.py", line 100, in wrapped
    return f(*args, **kwargs)
  File "<decorator-gen-52>", line 2, in get_roles
  File "/Users/philip/workspace/kbo/src-mrd/plone.api/src/plone/api/validation.py", line 131, in wrapped
    return f(*args, **kwargs)
  File "/Users/philip/workspace/kbo/src-mrd/plone.api/src/plone/api/group.py", line 235, in get_roles
    lrmanagers = plone_user._getLocalRolesPlugins()
AttributeError: 'super' object has no attribute '_getLocalRolesPlugins'
```

**Comment by pbauer** [comment]
Also: getting gobal roles for this Virtual Group does not work:
```
(Pdb++) api.group.grant_roles(groupname='Administrators', roles=['Editor'])
(Pdb++) api.group.get_roles(groupname='Administrators')
['Manager', 'Authenticated', 'Editor']
(Pdb++) api.group.grant_roles(groupname='AuthenticatedUsers', roles=['Editor'])
(Pdb++) api.group.get_roles(groupname='AuthenticatedUsers')
[]
```
The assignment itself actually works, it is only the getting that always returns a empty list.
