### ISSUE TITLE
plone.api.env.adopt_role does not remove security manager context when exception was raised within context manager 

### ISSUE THREAD

**Issue by neilferreira** [plone/plone.api#374]
In this example you can see that we're making use of adopt_roles 100 times in a single script, the fallback max stack size as per https://github.com/zopefoundation/AccessControl/blob/master/src/AccessControl/ImplPython.py#L535

```    def test_blah(self):
        x = 0
        while x <= 101:
            x = x + 1
            try:
                with plone.api.env.adopt_roles(['Manager']):
                    raise ValueError('wat')
            except ValueError:
                pass
```

This raises the following error:
```Error in test test_blah
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "tests/test_blah.py", line 1023, in test_blah
    with plone.api.env.adopt_roles(['Manager']):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "buildout-cache/eggs/plone.api-1.5.1-py2.7.egg/plone/api/env.py", line 118, in _adopt_roles
    sm.addContext(overriding_context)
  File "buildout-cache/eggs/AccessControl-3.0.11-py2.7-linux-x86_64.egg/AccessControl/ImplPython.py", line 604, in addContext
    raise SystemError, 'Excessive recursion'
SystemError: Excessive recursion
```

This can be fixed by amending this section of code (https://github.com/plone/plone.api/blob/master/src/plone/api/env.py#L120) to

```
    try:
        yield
    finally:
        sm.removeContext(overriding_context)
```

**Comment by ale-rt** [comment]
Thanks a lot @neilferreira for your excellent bug report.
Sorry that it took so long for this issue to be fixed: https://github.com/plone/plone.api/pull/493
