### ISSUE TITLE
Restore doctests

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.api#474]
Since the conversion to Myst Markdown in PR #470, the doctests are not found. I only realise this now.
In the coredev buildout, this now runs zero tests:

    bin/test -s plone.api -m test_doctests

When you checkout `plone.api` tag 2.0.0a2, the same command runs 187 tests.

One problem is that `test_doctests.py` looks for files in the `tests/doctests/` directory. All files in there are symlinks and they are now broken because they point to `*.rst` files in the `docs` directory. This should be `*.md` now.

But fixing the symlinks is not enough.  Python doctests expect a syntax with `>>>`:

```
>>> 1 + 1
2
```

With the conversion to Myst the syntax has changed, so no tests are found anymore, even with proper symlinks.

Wait, this is not true. In the previous tag I do not see `>>>`. Okay, apparently the Python code blocks are found, possibly by [`manuel`](https://github.com/plone/plone.api/blob/master/src/plone/api/tests/test_doctests.py#L96-L97)

Maybe `manuel` can be taught how to look for doctests written in Myst syntax?
Or maybe a slightly different syntax works for both doctests and the documentation?

I would hate to revert the PR, especially since fixes were done to the documentation afterwards. :-/

Or maybe we decide that the remaining unit tests are good enough? If so, then all the `invisible-code-blocks` in the documentation can be removed.
At this moment I have no opinion here.

**Comment by ksuess** [comment]
My mistake, I'll try to find a bridge between MyST and doctests testing. Or revert to restructuredText.

**Comment by stevepiercy** [comment]
I think this can be resolved by using something like this:

````
```{eval-rst}
.. invisible-code-block: python

    [commented Python code that now has a MyST comment mark of `%` at the start of each line.]

```
````

However I am missing something in the set up of `plone.api` to run the tests via `bin/test -s plone.api -m test_doctests`. I did the following from within my checkout:

```
python3.9 -m venv .
bin/pip install -e ."[tests]"
bin/test -s plone.api -m test_doctests
zsh: no such file or directory: bin/test
```

Neither the README.rst nor Contributing docs are much help.

**Comment by mauritsvanrees** [comment]
`bin/test` would be from within the Plone coredev buildout.

In the plone.api there is an outdated `tox.ini` and a to-be-removed `.travis.yml` so that does not help.

Try this:

```
python3.9 -m venv .
bin/pip install -r https://dist.plone.org/release/6.0-dev/requirements.txt
bin/pip install Plone plone.app.testing zope.testrunner -c https://dist.plone.org/release/6.0-dev/constraints.txt
bin/pip install -e ."[test]"
bin/zope-testrunner --test-path src/ -m test_doctests
```

**Comment by stevepiercy** [comment]
Thank you! Installation was fine.

I tweaked syntax to this in about.md:

````
```{eval-rst}
.. invisible-code-block:: python

    from plone import api
    from plone.api.exc import InvalidParameterError
    try:
        api.portal.set_registry_record('plone.use_email_as_login', True)
    except InvalidParameterError:
        portal = api.portal.get()
        portal.portal_properties.site_properties.use_email_as_login = True
```
````

Test runner runs, but:

```
$ bin/zope-testrunner --test-path src/ -m test_doctests
/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/plone/app/linkintegrity/utils.py:3: DeprecationWarning: IEditingSchema is deprecated. Moved to plone.base.interfaces, import from there instead (will be removed in Plone 7).
  from Products.CMFPlone.interfaces import IEditingSchema
/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/plone/app/linkintegrity/handlers.py:13: DeprecationWarning: IPloneSiteRoot is deprecated. Moved to plone.base.interfaces, import from there instead (will be removed in Plone 7).
  from Products.CMFPlone.interfaces import IPloneSiteRoot
/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/src/plone/api/tests/test_doctests.py:11: DeprecationWarning: Browser is deprecated. Please import from plone.testing.zope.
  from plone.testing.z2 import Browser
Total: 0 tests, 0 failures, 0 errors and 0 skipped in 0.000 seconds.
```

I expected at least 1 test discovered. Is there something else I can try?

**Comment by stevepiercy** [comment]
Oh, do I need to add a symlink for test discovery of `.md` files, or something like that?

> One problem is that `test_doctests.py` looks for files in the `tests/doctests/` directory. All files in there are symlinks and they are now broken because they point to `*.rst` files in the `docs` directory. This should be `*.md` now.

Where is the `tests/doctests/` directory supposed to be located?

**Comment by mauritsvanrees** [comment]
In Plone packages in 99 percent of the cases the tests directory is within the main code.  So in this case here:

[`src/plone/api/tests/doctests`](https://github.com/plone/plone.api/tree/master/src/plone/api/tests/doctests)

**Comment by mauritsvanrees** [comment]
BTW, the symlinking was done years ago in commit 4ebfd990c64cf152b80d6f0930e46fd0dc1cef9f.

I guess it is still needed: when you let `test_doctests.py` look in the `docs` directory instead of [in the directory with symlinks](https://github.com/plone/plone.api/blob/master/src/plone/api/tests/test_doctests.py#L114), I expect it will work fine when `plone.api` is an editable install from source, but not when install a released version: the code may then not be able to find the `docs` directory at all. But it is a guess.

**Comment by stevepiercy** [comment]
Success! With that one test I altered, that is. From within the `plone.api` root:

```
ln -s ../../../../../docs/about.md src/plone/api/tests/doctests/about.md
bin/zope-testrunner --test-path src/ -m test_doctests

<snip>
  Ran 1 tests with 0 failures, 0 errors and 0 skipped in 1.747 seconds.
<snip>
```

I will add a complete fix to https://github.com/plone/plone.api/pull/476

Thank you! Yay team!

**Comment by stevepiercy** [comment]
It looks like there are no doctests in `env.md`, so I omitted that from the list of symlinks. These are the only files (5 of them) that have `invisible-code-block: python` in them.

```
ln -s ../../../../../docs/about.md src/plone/api/tests/doctests/about.md
ln -s ../../../../../docs/content.md src/plone/api/tests/doctests/content.md
ln -s ../../../../../docs/group.md src/plone/api/tests/doctests/group.md
ln -s ../../../../../docs/portal.md src/plone/api/tests/doctests/portal.md
ln -s ../../../../../docs/user.md src/plone/api/tests/doctests/user.md
```

**Comment by stevepiercy** [comment]
There was one weird one. It is not clear whether there was an intent to add a doctest, but one was never added:

https://github.com/plone/plone.api/blame/bfcdcee0e12ff45221f2e6d4ffa8f87512e6ba57/docs/content.rst#L462

It's just a blank doctest. I removed it, but please let me know if there should be a doctest there.

**Comment by stevepiercy** [comment]
```
  Ran 94 tests with 0 failures, 5 errors and 0 skipped in 10.055 seconds.
```

That's the correct number of doctests, but I will leave the test failures to those who understand them to resolve them. Here's the trackebacks for those failures:

```
Error in test /Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/src/plone/api/tests/doctests/group.md
Traceback (most recent call last):
  File "/Users/stevepiercy/.pyenv/versions/3.9.0/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/stevepiercy/.pyenv/versions/3.9.0/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/Users/stevepiercy/.pyenv/versions/3.9.0/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/manuel/testing.py", line 43, in runTest
    self.regions.evaluate_with(self.manuel, self.globs)
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/manuel/__init__.py", line 135, in evaluate_with
    evaluater(region, self, globs)
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/manuel/codeblock.py", line 31, in execute_code_block
    exec(region.parsed.code, globs)
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/src/plone/api/tests/doctests/group.md:22", line 3, in <module>
NameError: name 'group' is not defined



Error in test /Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/src/plone/api/tests/doctests/content.md
Traceback (most recent call last):
  File "/Users/stevepiercy/.pyenv/versions/3.9.0/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/stevepiercy/.pyenv/versions/3.9.0/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/Users/stevepiercy/.pyenv/versions/3.9.0/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/manuel/testing.py", line 43, in runTest
    self.regions.evaluate_with(self.manuel, self.globs)
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/manuel/__init__.py", line 135, in evaluate_with
    evaluater(region, self, globs)
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/manuel/codeblock.py", line 31, in execute_code_block
    exec(region.parsed.code, globs)
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/src/plone/api/tests/doctests/content.md:58", line 3, in <module>
NameError: name 'api' is not defined

/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/plone/app/contenttypes/indexers.py:75: DeprecationWarning: Use plone.base.utils.safe_text instead (will be removed in Plone 7)
  safe_unicode(obj.id),
/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/plone/app/contenttypes/indexers.py:76: DeprecationWarning: Use plone.base.utils.safe_text instead (will be removed in Plone 7)
  safe_unicode(obj.title) or u'',
/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/plone/app/contenttypes/indexers.py:77: DeprecationWarning: Use plone.base.utils.safe_text instead (will be removed in Plone 7)
  safe_unicode(obj.description) or u'',
/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/plone/app/contenttypes/indexers.py:78: DeprecationWarning: Use plone.base.utils.safe_text instead (will be removed in Plone 7)
  safe_unicode(text),
/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/plone/app/contenttypes/indexers.py:79: DeprecationWarning: Use plone.base.utils.safe_text instead (will be removed in Plone 7)
  safe_unicode(subject),


Error in test /Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/src/plone/api/tests/doctests/portal.md
Traceback (most recent call last):
  File "/Users/stevepiercy/.pyenv/versions/3.9.0/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/stevepiercy/.pyenv/versions/3.9.0/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/Users/stevepiercy/.pyenv/versions/3.9.0/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/manuel/testing.py", line 43, in runTest
    self.regions.evaluate_with(self.manuel, self.globs)
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/manuel/__init__.py", line 135, in evaluate_with
    evaluater(region, self, globs)
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/manuel/codeblock.py", line 31, in execute_code_block
    exec(region.parsed.code, globs)
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/src/plone/api/tests/doctests/portal.md:66", line 3, in <module>
NameError: name 'nav_root' is not defined



Error in test /Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/src/plone/api/tests/doctests/user.md
Traceback (most recent call last):
  File "/Users/stevepiercy/.pyenv/versions/3.9.0/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/stevepiercy/.pyenv/versions/3.9.0/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/Users/stevepiercy/.pyenv/versions/3.9.0/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/manuel/testing.py", line 43, in runTest
    self.regions.evaluate_with(self.manuel, self.globs)
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/manuel/__init__.py", line 135, in evaluate_with
    evaluater(region, self, globs)
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/manuel/codeblock.py", line 31, in execute_code_block
    exec(region.parsed.code, globs)
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/src/plone/api/tests/doctests/user.md:35", line 3, in <module>
NameError: name 'user' is not defined



Error in test /Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/src/plone/api/tests/doctests/about.md
Traceback (most recent call last):
  File "/Users/stevepiercy/.pyenv/versions/3.9.0/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/stevepiercy/.pyenv/versions/3.9.0/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/Users/stevepiercy/.pyenv/versions/3.9.0/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/manuel/testing.py", line 43, in runTest
    self.regions.evaluate_with(self.manuel, self.globs)
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/manuel/__init__.py", line 135, in evaluate_with
    evaluater(region, self, globs)
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/lib/python3.9/site-packages/manuel/codeblock.py", line 31, in execute_code_block
    exec(region.parsed.code, globs)
  File "/Users/stevepiercy/projects/Plone/documentation/submodules/plone.api/src/plone/api/tests/doctests/about.md:82", line 4, in <module>
NameError: name 'catalog' is not defined
```

**Comment by stevepiercy** [comment]
Fixed in https://github.com/plone/plone.api/pull/476/commits/808ffe195621e27ccf2feff03f2f478e9096c5b9

I restarted Jenkins, and it should be all green again, unless it runs doctests as part of the run.

**Comment by ksuess** [comment]
I kicked out the doctests. Please let me the opportuntity to bring them back: I announced to provide a fix: https://github.com/plone/plone.api/issues/474#issuecomment-1092592575 and do not want to kick my work on manuel (extend to myst markdown) into the trash. Thanks.

**Comment by ksuess** [comment]
> My mistake, I'll try to find a bridge between MyST and doctests testing. Or revert to restructuredText.

The `manuel` package used by plone.api to test the _code block doctests_  is extended to read and handle MyST markdown syntax documentation. **I placed a request asking the maintainer to get a release** (and move to Plone, Zope or Collective repostiroy back again): https://github.com/benji-york/manuel/issues/24.
The manuel update is temporarily placed, until a release is made, here: https://github.com/rohberg/manuel

The update allows to include tests like the following.
Lines starting with '% ' are MyST markdown comments. 

````

## Get content object

There are several approaches to getting your content object.
Consider the following portal structure:

```
plone (portal root)
|-- blog
|-- about
|   |-- team
|   `-- contact
`-- events
    |-- training
    |-- conference
    `-- sprint
```

% invisible-code-block: python
%
% portal = api.portal.get()
% image = api.content.create(type='Image', id='image', container=portal)
% blog = api.content.create(type='Link', id='blog', container=portal)
% about = api.content.create(type='Folder', id='about', container=portal)
% events = api.content.create(type='Folder', id='events', container=portal)
%
% api.content.create(container=about, type='Document', id='team')
% api.content.create(container=about, type='Document', id='contact')
%
% api.content.create(container=events, type='Event', id='training')
% api.content.create(container=events, type='Event', id='conference')
% api.content.create(container=events, type='Event', id='sprint')

The following operations will get objects from the stucture above, including using {meth}`api.content.get`.

```python
# let's first get the portal object
from plone import api
portal = api.portal.get()
assert portal.id == 'plone'

# content can be accessed directly with dict-like access
blog = portal['blog']

# another way is to use ``get()`` method and pass it a path
about = api.content.get(path='/about')

# more examples
conference = portal['events']['conference']
sprint = api.content.get(path='/events/sprint')

# moreover, you can access content by its UID
uid = about['team'].UID()
team = api.content.get(UID=uid)

# returns None if UID cannot be found in catalog
not_found = api.content.get(UID='notfound')
```

% invisible-code-block: python
%
% self.assertTrue(portal)
% self.assertTrue(blog)
% self.assertTrue(about)
% self.assertTrue(conference)
% self.assertTrue(sprint)
% self.assertTrue(team)
% self.assertEquals(not_found, None)


````

**Comment by ksuess** [comment]
Short update on `manuel`: I reached out to the maintainer Benji York yesterday. In the meantime I updated my fork with docu and tests.  To proceed, I decided also to ping zopefoundation to ask if they are OK with reviving the zopefoundation/manuel original source repo(https://github.com/orgs/zopefoundation/teams/administrators/discussions/4).

Writing tests with `manuel` is awesome!!

**Comment by stevepiercy** [comment]
Fixed by https://github.com/plone/plone.api/pull/478
